import { render, screen } from "@testing-library/react"
import RootLayout, { metadata } from "@/app/layout"

// Mock the Providers component
jest.mock("@/providers/Providers", () => {
	const Providers = ({ children }: { children: React.ReactNode }) => (
		<div data-testid="mock-providers">{children}</div>
	)
	return Providers
})

describe("RootLayout", () => {
	beforeEach(() => {
		jest.clearAllMocks()
		console.error = jest.fn()
	})
	afterEach(() => {
		console.error = console.error
	})
	// Test metadata
	it("should define correct metadata", () => {
		expect(metadata).toEqual({
			title: "Create Next App",
			description: "Generated by create next app"
		})
	})

	// Test structure and attributes
	it("should render the correct HTML structure", () => {
		const { container } = render(
			<RootLayout>
				<p>Test Content</p>
			</RootLayout>
		)

		// Check the <html> element
		const htmlElement = container.querySelector("html")
		expect(htmlElement).toBeInTheDocument()
		expect(htmlElement).toHaveAttribute("lang", "en")
		expect(htmlElement).toHaveAttribute("id", "html")

		// Check the <body> element
		const bodyElement = container.querySelector("body")
		expect(bodyElement).toBeInTheDocument()
		expect(bodyElement).toHaveClass("className")

		// Check Providers wrapper
		const providersWrapper = screen.getByTestId("mock-providers")
		expect(providersWrapper).toBeInTheDocument()

		// Check children rendering
		expect(screen.getByText("Test Content")).toBeInTheDocument()
	})

	// Test Providers rendering
	it("should wrap children with Providers", () => {
		render(
			<RootLayout>
				<span>Inside Providers</span>
			</RootLayout>
		)

		// Check if the children exist within the Providers component
		const providersWrapper = screen.getByTestId("mock-providers")
		expect(providersWrapper).toContainElement(
			screen.getByText("Inside Providers")
		)
	})
})
